name: Release
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          community: "lethal-company"
          namespace: Renaud11232
          repo: thunderstore.io
          name: "Belirium_LC_QoL"
          description: "Quality of Life ModPack for the Belirium Studio"
          version: ${{ github.ref_name }}
          website: https://github.com/Renaud11232/Belirium_LC_QoL
          categories: |
            modpacks
          deps: |
            Renegades-FlashlightToggle@1.5.0
            Jamil-Corporate_Restructure@1.0.6
            nyhoot-ShipLoot@1.1.0
            Renegades-WalkieUse@1.5.0
            Monkeytype-HideChat@1.0.0
            RickArg-Helmet_Cameras@2.1.5
            
